#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# DuckDNS IP Auto-updater
# This file is generated by setup-gce.sh — do NOT commit it with real tokens!
# Installed at: /usr/local/bin/update-duckdns.sh
# Cron: */5 * * * * /usr/local/bin/update-duckdns.sh >> /var/log/duckdns.log 2>&1
# ═══════════════════════════════════════════════════════════════════════════

TOKEN="DUCKDNS_TOKEN_PLACEHOLDER"
SUBDOMAIN="DUCKDNS_SUBDOMAIN_PLACEHOLDER"

CURRENT_IP=$(curl -s --max-time 10 https://api.ipify.org 2>/dev/null)
if [ -z "$CURRENT_IP" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S') [ERROR] Could not determine external IP"
  exit 1
fi

RESULT=$(curl -s --max-time 10 \
  "https://www.duckdns.org/update?domains=${SUBDOMAIN}&token=${TOKEN}&ip=${CURRENT_IP}")

echo "$(date '+%Y-%m-%d %H:%M:%S') [${RESULT}] ${SUBDOMAIN}.duckdns.org → ${CURRENT_IP}"
